version: '3.9'

services:
  springboot-backend:
    build:
      context: .
    ports:
      - "8089:8089"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/devopsExam
      SPRING_DATASOURCE_USERNAME: devops_user
      SPRING_DATASOURCE_PASSWORD: devops_password
    networks:
      - app-network
    logging:  # Enhanced logging configuration
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    restart: always  # Automatically restart the service on failure

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: devopsExam
      MYSQL_USER: devops_user
      MYSQL_PASSWORD: devops_password
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:  # Add health check for MySQL
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    restart: always
    ports:
      - "9000:9000"
    environment:
      SONARQUBE_JDBC_URL: jdbc:mysql://mysql:3306/sonar
      SONARQUBE_JDBC_USERNAME: sonar
      SONARQUBE_JDBC_PASSWORD: sonar
    networks:
      - app-network
    depends_on:
      - mysql

  nexus:
    image: sonatype/nexus3:latest
    container_name: nexus_new
    restart: always
    ports:
      - "8081:8081"
    volumes:
      - nexus-data:/nexus-data
    networks:
      - app-network

volumes:
  mysql-data:
  nexus-data:

networks:
  app-network:
    driver: bridge

