name: Version Increment and Build

on:
  push:
    branches:
      - main  # You can change this to any branch you want to monitor

jobs:
  increment_version:
    runs-on: ubuntu-latest  # The job will run on the latest Ubuntu environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # This checks out the code from the repository

      - name: Get current version and increment
        run: |
          # Extract the current version from the pom.xml using grep
          VERSION=$(grep -oPm1 "(?<=<version>)(.*)(?=</version>)" pom.xml)

          # Extract the numeric version (e.g., 1.4.8)
          VERSION_NUMBER=$(echo $VERSION | sed -E 's/([0-9]+\.[0-9]+\.[0-9]+)-RELEASE/\1/')
          
          # Split the version number and increment the patch version
          IFS='.' read -r -a VERSION_ARRAY <<< "$VERSION_NUMBER"
          VERSION_ARRAY[2]=$((VERSION_ARRAY[2] + 1))  # Increment patch version
          NEW_VERSION="${VERSION_ARRAY[0]}.${VERSION_ARRAY[1]}.${VERSION_ARRAY[2]}-RELEASE"

          # Update the version in pom.xml
          sed -i "s/<version>$VERSION<\/version>/<version>$NEW_VERSION<\/version>/" pom.xml
          echo "Updated version to $NEW_VERSION"

      - name: Commit the updated version
        run: |
          # Configure Git user for committing changes
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          # Add the updated pom.xml to Git
          git add pom.xml

          # Commit the changes
          git commit -m "Bump version to $NEW_VERSION"

          # Push the changes back to the repository
          git push
